config/routes.rb
Rails.application.routes.draw do
  root "random_fortune#index"

  namespace :api do
    resources :fortunes
  end

  resources :fortunes, only: [:index, :create]
  resource :random_fortune, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fortune.rb
class Fortune < ApplicationRecord
  validates :content, presence: true
end

app/controllers/api/fortunes_controller.rb
class API::FortunesController < ActionController::API
  def index
    @fortunes = Fortune.order(created_at: :desc).limit(10)
    render json: { fortunes: @fortunes }
  end

  def show
    @fortune = Fortune.find(params[:id])
    render json: { fortunes: @fortune }
  end

  def create
    @fortune = Fortune.new(fortune_params)

    if @fortune.save
      render json: { fortunes: @fortune },
        status: :created,
        location: api_fortune_url(@fortune)
    else
      render json: @fortune.errors,
        status: :unprocessable_entity
    end
  end

  def update
    @fortune = Fortune.find(params[:id])
    if @fortune.update(fortune_params)
      render json: { fortunes: @fortune }
    else
      render json: @fortune.errors,
        status: :unprocessable_entity
    end
  end

  def destroy
    # binding.pry
    @fortune = Fortune.find(params[:id])
    @fortune.destroy
  end

  def create
    @fortune = Fortune.new(fortune_params)

    if @fortune.save
      render json: { fortunes: @fortune },
        status: :created,
        location: api_fortune_url(@fortune)
    else
      render json: @fortune.errors,
        status: :unprocessable_entity
    end
  end

  private
  def fortune_params
    params.require(:fortune).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  def index
    @fortunes = Fortune.order(created_at: :desc).limit(10)
  end

  def create
    @fortune = Fortune.new(fortune_params)
    if @fortune.save
      flash[:success] = "Fortune created!"
      redirect_to fortunes_path
    else
      @fortunes = Fortune.order(created_at: :desc).limit(10)
      flash[:alert] = @fortune.errors.full_messages.join(". ")
      render :index
    end
  end

  private
  def fortune_params
    params.require(:fortune).permit(:content)
  end
end

app/controllers/random_fortune_controller.rb
class RandomFortuneController < ApplicationController
  def index
    @fortune = Fortune.all.sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fortunes/index.html.erb
<h1>Fortunes</h1>

<div class="fortunes">
  <% @fortunes.each do |fortune| %>
    <div class="callout success"  >
      <%= fortune.content %>
      <%= button_to "delete", api_fortune_path(fortune), :method => :delete, id: "#{fortune.id}"%>
    </div>
  <% end %>
</div>

<hr />

<h3>New Fortune</h3>
<%= form_for :fortune, html: { id: :new_fortune } do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="callout <%= type %>">
    <button class="close-button" aria-label="Close alert" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Fortune Teller</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row main">
      <div class="small-6 small-offset-3 columns">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/random_fortune/index.html.erb
<h2>Your Fortune is...</h2>

<div class="callout success">
  <%= @fortune.content %>
</div>

<div>
  <%= link_to "All Fortunes", fortunes_path %>
</div>